import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body
        className="min-h-screen text-white"
        style={{
          background: `
            radial-gradient(60% 60% at 20% 20%, rgba(139,92,246,0.35) 0%, transparent 60%),
            radial-gradient(50% 50% at 80% 30%, rgba(56,189,248,0.35) 0%, transparent 55%),
            linear-gradient(180deg, #0b0f1a 0%, #0a0e18 100%)
          `,
        }}
      >
        {children}
      </body>
    </html>
  );
}
